// Code generated by MockGen. DO NOT EDIT.
// Source: ./gen/go/stream/stream_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=./gen/go/stream/stream_service_grpc.pb.go -destination=./internal/service/mock/stream_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	stream "github.com/mrhumster/transcoder-service/gen/go/stream"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockStreamServiceClient is a mock of StreamServiceClient interface.
type MockStreamServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServiceClientMockRecorder
	isgomock struct{}
}

// MockStreamServiceClientMockRecorder is the mock recorder for MockStreamServiceClient.
type MockStreamServiceClientMockRecorder struct {
	mock *MockStreamServiceClient
}

// NewMockStreamServiceClient creates a new mock instance.
func NewMockStreamServiceClient(ctrl *gomock.Controller) *MockStreamServiceClient {
	mock := &MockStreamServiceClient{ctrl: ctrl}
	mock.recorder = &MockStreamServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamServiceClient) EXPECT() *MockStreamServiceClientMockRecorder {
	return m.recorder
}

// UpdateStreamMetadata mocks base method.
func (m *MockStreamServiceClient) UpdateStreamMetadata(ctx context.Context, in *stream.UpdateStreamMetadataRequest, opts ...grpc.CallOption) (*stream.UpdateStreamMetadataResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStreamMetadata", varargs...)
	ret0, _ := ret[0].(*stream.UpdateStreamMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamMetadata indicates an expected call of UpdateStreamMetadata.
func (mr *MockStreamServiceClientMockRecorder) UpdateStreamMetadata(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamMetadata", reflect.TypeOf((*MockStreamServiceClient)(nil).UpdateStreamMetadata), varargs...)
}

// UpdateStreamProcessing mocks base method.
func (m *MockStreamServiceClient) UpdateStreamProcessing(ctx context.Context, in *stream.UpdateStreamProcessingRequest, opts ...grpc.CallOption) (*stream.UpdateStreamProcessingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStreamProcessing", varargs...)
	ret0, _ := ret[0].(*stream.UpdateStreamProcessingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamProcessing indicates an expected call of UpdateStreamProcessing.
func (mr *MockStreamServiceClientMockRecorder) UpdateStreamProcessing(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamProcessing", reflect.TypeOf((*MockStreamServiceClient)(nil).UpdateStreamProcessing), varargs...)
}

// UpdateStreamStatus mocks base method.
func (m *MockStreamServiceClient) UpdateStreamStatus(ctx context.Context, in *stream.UpdateStreamStatusRequest, opts ...grpc.CallOption) (*stream.UpdateStreamStatusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStreamStatus", varargs...)
	ret0, _ := ret[0].(*stream.UpdateStreamStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamStatus indicates an expected call of UpdateStreamStatus.
func (mr *MockStreamServiceClientMockRecorder) UpdateStreamStatus(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamStatus", reflect.TypeOf((*MockStreamServiceClient)(nil).UpdateStreamStatus), varargs...)
}

// MockStreamServiceServer is a mock of StreamServiceServer interface.
type MockStreamServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockStreamServiceServerMockRecorder
	isgomock struct{}
}

// MockStreamServiceServerMockRecorder is the mock recorder for MockStreamServiceServer.
type MockStreamServiceServerMockRecorder struct {
	mock *MockStreamServiceServer
}

// NewMockStreamServiceServer creates a new mock instance.
func NewMockStreamServiceServer(ctrl *gomock.Controller) *MockStreamServiceServer {
	mock := &MockStreamServiceServer{ctrl: ctrl}
	mock.recorder = &MockStreamServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamServiceServer) EXPECT() *MockStreamServiceServerMockRecorder {
	return m.recorder
}

// UpdateStreamMetadata mocks base method.
func (m *MockStreamServiceServer) UpdateStreamMetadata(arg0 context.Context, arg1 *stream.UpdateStreamMetadataRequest) (*stream.UpdateStreamMetadataResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamMetadata", arg0, arg1)
	ret0, _ := ret[0].(*stream.UpdateStreamMetadataResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamMetadata indicates an expected call of UpdateStreamMetadata.
func (mr *MockStreamServiceServerMockRecorder) UpdateStreamMetadata(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamMetadata", reflect.TypeOf((*MockStreamServiceServer)(nil).UpdateStreamMetadata), arg0, arg1)
}

// UpdateStreamProcessing mocks base method.
func (m *MockStreamServiceServer) UpdateStreamProcessing(arg0 context.Context, arg1 *stream.UpdateStreamProcessingRequest) (*stream.UpdateStreamProcessingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamProcessing", arg0, arg1)
	ret0, _ := ret[0].(*stream.UpdateStreamProcessingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamProcessing indicates an expected call of UpdateStreamProcessing.
func (mr *MockStreamServiceServerMockRecorder) UpdateStreamProcessing(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamProcessing", reflect.TypeOf((*MockStreamServiceServer)(nil).UpdateStreamProcessing), arg0, arg1)
}

// UpdateStreamStatus mocks base method.
func (m *MockStreamServiceServer) UpdateStreamStatus(arg0 context.Context, arg1 *stream.UpdateStreamStatusRequest) (*stream.UpdateStreamStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStreamStatus", arg0, arg1)
	ret0, _ := ret[0].(*stream.UpdateStreamStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStreamStatus indicates an expected call of UpdateStreamStatus.
func (mr *MockStreamServiceServerMockRecorder) UpdateStreamStatus(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStreamStatus", reflect.TypeOf((*MockStreamServiceServer)(nil).UpdateStreamStatus), arg0, arg1)
}

// mustEmbedUnimplementedStreamServiceServer mocks base method.
func (m *MockStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedStreamServiceServer")
}

// mustEmbedUnimplementedStreamServiceServer indicates an expected call of mustEmbedUnimplementedStreamServiceServer.
func (mr *MockStreamServiceServerMockRecorder) mustEmbedUnimplementedStreamServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedStreamServiceServer", reflect.TypeOf((*MockStreamServiceServer)(nil).mustEmbedUnimplementedStreamServiceServer))
}

// MockUnsafeStreamServiceServer is a mock of UnsafeStreamServiceServer interface.
type MockUnsafeStreamServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeStreamServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeStreamServiceServerMockRecorder is the mock recorder for MockUnsafeStreamServiceServer.
type MockUnsafeStreamServiceServerMockRecorder struct {
	mock *MockUnsafeStreamServiceServer
}

// NewMockUnsafeStreamServiceServer creates a new mock instance.
func NewMockUnsafeStreamServiceServer(ctrl *gomock.Controller) *MockUnsafeStreamServiceServer {
	mock := &MockUnsafeStreamServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeStreamServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeStreamServiceServer) EXPECT() *MockUnsafeStreamServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedStreamServiceServer mocks base method.
func (m *MockUnsafeStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedStreamServiceServer")
}

// mustEmbedUnimplementedStreamServiceServer indicates an expected call of mustEmbedUnimplementedStreamServiceServer.
func (mr *MockUnsafeStreamServiceServerMockRecorder) mustEmbedUnimplementedStreamServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedStreamServiceServer", reflect.TypeOf((*MockUnsafeStreamServiceServer)(nil).mustEmbedUnimplementedStreamServiceServer))
}
