# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoder-service
  namespace: go-app
  labels:
    app: transcoder-service
spec:
  selector:
    matchLabels:
      app: transcoder-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: transcoder-service
      labels:
        app: transcoder-service
    spec:
      containers:
        - name: transcoder-service
          image: xomrkob/transcoder-service:latest
          volumeMounts:
            - mountPath: /tmp
              name: tmp-disk
          imagePullPolicy:
          resources:
            requests:
              cpu: 800m
              memory: 512Mi
            limits:
              cpu: 4000m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "ps aux | grep worker"]
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: STREAM_SERVICE_ADDR
              value: stream-service:50051
            - name: REDIS_ADDR
              value: casbin-redis-master:6379
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: casbin-redis
                  key: redis-password
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: go-app-config
                  key: MINIO_ENDPOINT
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: go-app-config
                  key: MINIO_BUCKET_NAME
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  name: go-app-config
                  key: MINIO_USE_SSL
            - name: MINIO_REGION
              valueFrom:
                configMapKeyRef:
                  name: go-app-config
                  key: MINIO_REGION
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
      volumes:
        - name: tmp-disk
          emptyDir:
            sizeLimit: 2Gi
      restartPolicy: Always
---

