# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoder-service
  namespace: go-app
  labels:
    app: transcoder-service
spec:
  selector:
    matchLabels:
      app: transcoder-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: transcoder-service
      labels:
        app: transcoder-service
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
        - name: transcoder-service
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          image: xomrkob/transcoder-service:latest
          volumeMounts:
            - mountPath: /tmp
              name: tmp-disk
          imagePullPolicy:
          resources:
            requests:
              cpu: 800m
              memory: 512Mi
            limits:
              cpu: 4000m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "ps aux | grep worker"]
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: transcoder-service-config
            - configMapRef:
                name: go-app-config
            - secretRef:
                name: casbin-redis
            - secretRef:
                name: minio-credentials
      volumes:
        - name: tmp-disk
          emptyDir:
            sizeLimit: 10Gi
      restartPolicy: Always
---
