apiVersion: v1
kind: Service
metadata:
  name: transcoder-service
  namespace: go-app
  labels:
    app: transcoder-service
spec:
  selector:
    app: transcoder-service
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics