// Code generated by MockGen. DO NOT EDIT.
// Source: minio_client.go
//
// Generated by this command:
//
//	mockgen -source=minio_client.go -destination=mock/minio_client_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	minio "github.com/minio/minio-go/v7"
	gomock "go.uber.org/mock/gomock"
)

// MockMinIOClient is a mock of MinIOClient interface.
type MockMinIOClient struct {
	ctrl     *gomock.Controller
	recorder *MockMinIOClientMockRecorder
	isgomock struct{}
}

// MockMinIOClientMockRecorder is the mock recorder for MockMinIOClient.
type MockMinIOClientMockRecorder struct {
	mock *MockMinIOClient
}

// NewMockMinIOClient creates a new mock instance.
func NewMockMinIOClient(ctrl *gomock.Controller) *MockMinIOClient {
	mock := &MockMinIOClient{ctrl: ctrl}
	mock.recorder = &MockMinIOClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinIOClient) EXPECT() *MockMinIOClientMockRecorder {
	return m.recorder
}

// FGetObject mocks base method.
func (m *MockMinIOClient) FGetObject(ctx context.Context, bucketName, objectName, filePath string, opts minio.GetObjectOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FGetObject", ctx, bucketName, objectName, filePath, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// FGetObject indicates an expected call of FGetObject.
func (mr *MockMinIOClientMockRecorder) FGetObject(ctx, bucketName, objectName, filePath, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FGetObject", reflect.TypeOf((*MockMinIOClient)(nil).FGetObject), ctx, bucketName, objectName, filePath, opts)
}

// FPutObject mocks base method.
func (m *MockMinIOClient) FPutObject(ctx context.Context, bucketName, objectName, filePath string, opts minio.PutObjectOptions) (minio.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FPutObject", ctx, bucketName, objectName, filePath, opts)
	ret0, _ := ret[0].(minio.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FPutObject indicates an expected call of FPutObject.
func (mr *MockMinIOClientMockRecorder) FPutObject(ctx, bucketName, objectName, filePath, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FPutObject", reflect.TypeOf((*MockMinIOClient)(nil).FPutObject), ctx, bucketName, objectName, filePath, opts)
}
