// Code generated by MockGen. DO NOT EDIT.
// Source: mux.go
//
// Generated by this command:
//
//	mockgen -source=mux.go -destination=mock/muxer_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMuxer is a mock of Muxer interface.
type MockMuxer struct {
	ctrl     *gomock.Controller
	recorder *MockMuxerMockRecorder
	isgomock struct{}
}

// MockMuxerMockRecorder is the mock recorder for MockMuxer.
type MockMuxerMockRecorder struct {
	mock *MockMuxer
}

// NewMockMuxer creates a new mock instance.
func NewMockMuxer(ctrl *gomock.Controller) *MockMuxer {
	mock := &MockMuxer{ctrl: ctrl}
	mock.recorder = &MockMuxerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxer) EXPECT() *MockMuxerMockRecorder {
	return m.recorder
}

// MuxToMP4 mocks base method.
func (m *MockMuxer) MuxToMP4(ctx context.Context, playlistPath, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuxToMP4", ctx, playlistPath, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// MuxToMP4 indicates an expected call of MuxToMP4.
func (mr *MockMuxerMockRecorder) MuxToMP4(ctx, playlistPath, outputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuxToMP4", reflect.TypeOf((*MockMuxer)(nil).MuxToMP4), ctx, playlistPath, outputPath)
}
