// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=mock/processor_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	processor "github.com/mrhumster/transcoder-service/internal/processor"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoProcessor is a mock of VideoProcessor interface.
type MockVideoProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockVideoProcessorMockRecorder
	isgomock struct{}
}

// MockVideoProcessorMockRecorder is the mock recorder for MockVideoProcessor.
type MockVideoProcessorMockRecorder struct {
	mock *MockVideoProcessor
}

// NewMockVideoProcessor creates a new mock instance.
func NewMockVideoProcessor(ctrl *gomock.Controller) *MockVideoProcessor {
	mock := &MockVideoProcessor{ctrl: ctrl}
	mock.recorder = &MockVideoProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoProcessor) EXPECT() *MockVideoProcessorMockRecorder {
	return m.recorder
}

// GetDuration mocks base method.
func (m *MockVideoProcessor) GetDuration(ctx context.Context, inputPath string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDuration", ctx, inputPath)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDuration indicates an expected call of GetDuration.
func (mr *MockVideoProcessorMockRecorder) GetDuration(ctx, inputPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDuration", reflect.TypeOf((*MockVideoProcessor)(nil).GetDuration), ctx, inputPath)
}

// TranscodeToHLS mocks base method.
func (m *MockVideoProcessor) TranscodeToHLS(ctx context.Context, inputPath, outputDir string) (<-chan processor.Progress, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranscodeToHLS", ctx, inputPath, outputDir)
	ret0, _ := ret[0].(<-chan processor.Progress)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// TranscodeToHLS indicates an expected call of TranscodeToHLS.
func (mr *MockVideoProcessorMockRecorder) TranscodeToHLS(ctx, inputPath, outputDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranscodeToHLS", reflect.TypeOf((*MockVideoProcessor)(nil).TranscodeToHLS), ctx, inputPath, outputDir)
}
